---

gcp_project: "acs-san-stackroxci"
gcp_auth_kind: "serviceaccount"
gcp_service_account_file: /tmp/secret/stackrox-collector-e2e-tests/GOOGLE_CREDENTIALS_COLLECTOR_SVC_ACCT
gcp_instance_prefix: collector-ci
gcp_available_zones:
  - us-central1-a
  - us-central1-b
  - us-central1-c
  - us-central1-f
ansible_user: runner
gcp_network_name: collector-ci

gcp_default_labels:
  stackrox-ci: "true"

ibm_output_inventory_file: "{{ lookup('env', 'PWD') }}/ci/inventory_ibmcloud.yml"
ibm_disk_size: 32
