version: '3'

services:
  apt-cacher-ng:
    image: sameersbn/apt-cacher-ng
    container_name: apt-cacher-ng
    ports:
      - "3142:3142"
    volumes:
      - ~/.srbcache/root/apt-cacher-ng:/var/cache/apt-cacher-ng
  testaptgetter:
    build: testaptgetter
    depends_on:
      - apt-cacher-ng
    volumes:
      - ~/.srbcache:/mnt/srbcache
      - ~/.srbcache/nonroot/ccache:/home/srbuser/.ccache
      - /var/run/docker.sock:/var/run/docker.sock

