name: Build and push support-packages

on:
  workflow_call:
    inputs:
      branch-name:
        type: string
        required: true
        description: Branch CI is running on
      drivers-bucket:
        type: string
        required: true
        description: Bucket holding the drivers to package
      support-packages-bucket:
        type: string
        required: true
        description: Bucket where support-packages will be pushed to
      public-support-packages-bucket:
        type: string
        required: true
        description: Public bucket where support-packages will be pushed to


jobs:
  build-support-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_COLLECTOR_SVC_ACCT }}'

      - uses: ./.github/actions/support-package-metadata
        with:
          branch-name: ${{ inputs.branch-name }}

      - name: Create support-packages
        run: |
          ${{ github.workspace }}/kernel-modules/support-packages/04-create-support-packages.sh \
            ${{ github.workspace }}/collector/LICENSE-kernel-modules.txt \
            gs://${{ inputs.drivers-bucket }} \
            /tmp/support-packages/metadata \
            /tmp/support-packages/output

      - name: Push support-packages
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: /tmp/support-packages/output
          parent: false
          destination: ${{ inputs.support-packages-bucket }}

      - name: Push support-packages to public bucket
        uses: 'google-github-actions/upload-cloud-storage@v1'
        if: github.event_name == 'push'
        with:
          path: /tmp/support-packages/output
          parent: false
          destination: ${{ inputs.public-support-packages-bucket }}

      - uses: ./.github/actions/support-package-index
        with:
          gcp-bucket: ${{ inputs.support-packages-bucket }}
          metadata-path: /tmp/support-packages/metadata
          output-path: /tmp/support-packages/output

      - name: Push index.html
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: /tmp/support-packages/output/index.html
          parent: false
          destination: ${{ inputs.support-packages-bucket }}

      - name: Push index.html to public bucket
        uses: 'google-github-actions/upload-cloud-storage@v1'
        if: github.event_name == 'push'
        with:
          path: /tmp/support-packages/output/index.html
          parent: false
          destination: ${{ inputs.public-support-packages-bucket }}

      - name: Slack notification
        if: failure() && github.event_name == 'push'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_ONCALL }}
          SLACK_CHANNEL: oncall
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_TITLE: Support package job failed
          MSG_MINIMAL: actions url,commit
          SLACK_MESSAGE: |
            @collector-team
